### ISSUE TITLE
Errors when running ScaffMatch

### ISSUE THREAD

**Issue by wangshun1121** [adigenova/fastsg#2]
I installed ScaffMatch and tried examples affiliated to this package.

```
cd ./ScaffMatch/example
bash scaffmatch_aureus.sh mappings
```

and got following errors:

```
Running ScaffMatch
2018-08-31 16:59:37,318 - INFO - **--**--**--**--**--**--**--**--**--**--**--**--**--**--**--**--**
2018-08-31 16:59:37,319 - INFO - Settings used for this run of ScaffMatch are:
2018-08-31 16:59:37,319 - INFO -     scaff_dir  -- /usr/local/ScaffMatchX/examples/S_aureus/output/aureus
2018-08-31 16:59:37,319 - INFO -     ctg_fasta  -- /usr/local/ScaffMatchX/examples/S_aureus/contigs.fasta
2018-08-31 16:59:37,319 - INFO -     libraries  -- {1: {'std': 300, 'sam2': '/usr/local/ScaffMatchX/examples/S_aureus/mapped_reads_2.sam', 'sam1': '/usr/local/ScaffMatchX/examples/S_aureus/mapped_reads_1.sam', 'pm': 'rf', 'ins': 3600}}
2018-08-31 16:59:37,319 - INFO -     bundle_threshold  -- 5
2018-08-31 16:59:37,319 - INFO -     log_file  -- NONE
2018-08-31 16:59:37,319 - INFO - Stage I: Construct scaffolding graph
Traceback (most recent call last):
  File "/usr/bin/ScaffMatch/scaffmatch.py", line 140, in <module>
    scaffolder.scaffold()
  File "/usr/bin/ScaffMatch/pipeline/pipeline.py", line 49, in scaffold
    scaffgraph = self._graph_contruction()
  File "/usr/bin/ScaffMatch/pipeline/pipeline.py", line 25, in _graph_contruction
    return gconstructor.scaffolding_graph()
  File "/usr/bin/ScaffMatch/alignment/graph.py", line 45, in scaffolding_graph
    self._contigs_coverage()
  File "/usr/bin/ScaffMatch/alignment/graph.py", line 306, in _contigs_coverage
    self._IGORgraph.add_node(name + "_1", {'seq': seq, 'width': l}) # first strand
TypeError: add_node() takes exactly 2 arguments (3 given)
```
it seems that line 306 at ./ScaffMatch/alignment/graph.py has some errors. 

I wonder have you ever met such problem when running ScaffMatch, and is there any solution?

**Comment by wangshun1121** [comment]
by the way, the networkx I installed is version 2.1

**Comment by wangshun1121** [comment]
Well, it seems this issue was solved. I reinstalled networkx v 1.7:
```
pip install -v networkx==1.7
```
and managed to run example!

**Comment by adigenova** [comment]
Nice.
Best
Alex
